databases:
  - name: 24hours_Doctor
    databaseName: 24hours_Doctor
    user: db_24hours_doctor_user

services:
  - type: web
    name: 24hours_Doctor
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 24hours_Doctor
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false